version: '3'

services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - mynet
  api:
    build:
      context: api
    deploy:
      replicas: 2
    ports:
      - "8080"
    links:
      - redis
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysqlData:/mysqlData
    networks:
      - mynet

  web:
    build:
      context: website
    deploy:
      replicas: 2
    ports:
      - "8081"
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysqlData:/mysqlData   
    networks:
      - mynet
  
  redis:
    image: redis
    restart: always
    networks:
      - mynet

  mysql:
    image: mysql
    ports:
      - "3306"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - mynet
    volumes:
      - ./mysqlData:/var/lib/mysql
      
    command: [ "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--bind-address=0.0.0.0",
      "--require_secure_transport=ON",
      "--ssl-ca=/var/lib/mysql/ca.pem",
      "--ssl-cert=/var/lib/mysql/server-cert.pem",
      "--ssl-key=/var/lib/mysql/server-key.pem",
      "--default_authentication_plugin=mysql_native_password" ]

networks:
  mynet:
    driver: bridge

  

